backend:
    name: git-gateway
    branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
media_folder: "src/media" # Media files will be stored in the repo under src/media
public_folder: "/media" # The src attribute for uploaded media will begin with /media
collections:
    -   name: "blog" # Used in routes, e.g., /admin/collections/blog
        label: "Blog" # Used in the UI
        folder: "src/data/blog" # The path to the folder where the documents are stored
        create: true # Allow users to create new documents in this collection
        slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
        fields: # The fields for each document, usually in front matter
            - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
            - { label: "Title", name: "title", widget: "string" }
            - { label: "Publish Date", name: "date", widget: "datetime" }
            - { label: "Featured Image", name: "hero_image", widget: "image" }
            - { label: "Rating (scale of 1-5)", name: "rating", widget: "number" }
            - { label: "Body", name: "body", widget: "markdown" }
    -   label: "Pages"
        name: "pages"
        files:
            -   label: "Home"
                name: "home"
                file: "src/data/index.md"
                fields:
                    - { label: Title, name: title, widget: string }
                    - { label: Language, name: lang, widget: select, options: [ "en" ] }
                    - { label: Description, name: description, widget: string }
                    - { label: Body, name: body, widget: markdown }
